### ISSUE TITLE
Dispenser - Arrow Crash

### ISSUE THREAD

**Issue by grimmtastic** [GrapeStudios/Hexalia#2]
Was in a jungle dungeon and tripped a dispenser and once the arrow hit me, the game crashed.
[crash-2024-04-30_00.28.06-server.txt](https://github.com/GrapeStudios/Hexalia/files/15158658/crash-2024-04-30_00.28.06-server.txt)

**Comment by SirColor** [comment]
Hi, thanks for the notice, I have fixed this issue on the code now. This should be fixed in the upcoming update.

The issue seems to be with the casting of the attacker to LivingEntity. The error is due to the attacker not always being a LivingEntity. To fix this, I made sure that it checks if the attacker is indeed a LivingEntity before casting.

**Comment by SirColor** [comment]
Hi, thanks for the notice, I have fixed this issue on the code now. This should be fixed in the upcoming update.

The issue seems to be with the casting of the attacker to LivingEntity. The error is due to the attacker not always being a LivingEntity. To fix this, I made sure that it checks if the attacker is indeed a LivingEntity before casting.
